### ISSUE TITLE
Disease Ontology structure

### ISSUE THREAD

**Issue by sebotic** [SuLab/scheduled-bots#17]
There is an issue with how Disease Ontology is structured. Way too many items are subclass of disease  (https://www.wikidata.org/wiki/Q12136). It should be 8 items, but [it's 156](http://tinyurl.com/y9zrwgur). This makes traversal though the ontology structure impossible bc one gets to the top just trough one edge.

**Comment by stuppie** [comment]
This is due to us not removing old statements. See issue here: https://github.com/SuLab/GeneWikiCentral/issues/20. I'm almost done modifying WDI to handle fastrun with references ([link](https://github.com/SuLab/WikidataIntegrator/tree/fastrun_ref)), and then will change the bots to remove old statements like this.

All of these subclass of disease are either unreferenced (added by someone else) or from previous/old version of DO. See [query](http://tinyurl.com/ycydpqrn). As a workaround for this particular query, you could filter for statements that are retrieved after Jan 1, 2017

**Comment by stuppie** [comment]
Should be fixed now: http://tinyurl.com/y84xabvv
